plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: minima
title: Ivan’s Notes and Musings
description: A collection of insights and thoughts on software testing, automation, and more from an SDET’s perspective
navigation:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Notes
    link: /notes/
  - name: Contact
    link: /contact/